/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    agencies: Agency;
    'service-centers': ServiceCenter;
    documents: Document;
    sources: Source;
    transactions: Transaction;
    claims: Claim;
    'audit-events': AuditEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    agencies: AgenciesSelect<false> | AgenciesSelect<true>;
    'service-centers': ServiceCentersSelect<false> | ServiceCentersSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    claims: ClaimsSelect<false> | ClaimsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  adminLabel?: string | null;
  name?: string | null;
  displayName?: string | null;
  /**
   * admin · reviewer · researcher · viewer — الباحث لا ينشر. المراجع والمدير ينشران.
   */
  role: 'admin' | 'reviewer' | 'researcher' | 'viewer';
  isActive?: boolean | null;
  preferredLocale?: ('ar' | 'en') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * معرّف ثابت غير مترجم. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية.
   */
  slug: string;
  description?: string | null;
  /**
   * اتركه فارغاً إن لم يكن هناك تصنيف أب (يُعرض: بدون تصنيف أب).
   */
  parent?: (number | null) | Category;
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies".
 */
export interface Agency {
  id: number;
  name: string;
  shortName?: string | null;
  /**
   * معرّف ثابت غير مترجم. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية.
   */
  slug: string;
  type: 'ministry' | 'directorate' | 'public_institution' | 'municipality' | 'syndicate' | 'university' | 'other';
  description?: string | null;
  officialWebsite?: string | null;
  contactEmail?: string | null;
  phones?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  mainAddress?: string | null;
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-centers".
 */
export interface ServiceCenter {
  id: number;
  name: string;
  /**
   * معرّف ثابت غير مترجم. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية.
   */
  slug: string;
  agency: number | Agency;
  /**
   * قائمة ثابتة — لا يُستنتج موقع المستخدم تلقائياً.
   */
  governorate:
    | 'damascus'
    | 'rif_dimashq'
    | 'aleppo'
    | 'homs'
    | 'hama'
    | 'latakia'
    | 'tartus'
    | 'idlib'
    | 'deir_ez_zor'
    | 'al_hasakah'
    | 'al_raqqah'
    | 'daraa'
    | 'as_suwayda'
    | 'quneitra';
  city: string;
  address: string;
  phones?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  workingHours?: string | null;
  accessibilityNotes?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * وثائق يحتاجها المواطن للمعاملات — ليست ملفات مرفوعة.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  name: string;
  /**
   * معرّف ثابت غير مترجم. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية.
   */
  slug: string;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  documentType?:
    | (
        | 'identity'
        | 'civil_record'
        | 'application'
        | 'photograph'
        | 'receipt'
        | 'certificate'
        | 'approval'
        | 'contract'
        | 'form'
        | 'other'
      )
    | null;
  validityNote?: string | null;
  reusable?: boolean | null;
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  title: string;
  /**
   * معرّف ثابت غير مترجم. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية.
   */
  slug: string;
  sourceType:
    | 'official_webpage'
    | 'law'
    | 'decree'
    | 'decision'
    | 'circular'
    | 'official_form'
    | 'official_pdf'
    | 'announcement'
    | 'other';
  agency?: (number | null) | Agency;
  officialUrl: string;
  archiveUrl?: string | null;
  referenceNumber?: string | null;
  issuedAt?: string | null;
  lastVerifiedAt?: string | null;
  verificationStatus: 'needs_review' | 'verified' | 'outdated' | 'unavailable';
  /**
   * ملاحظات تحريرية — لا تُعرض للعامة.
   */
  notes?: string | null;
  /**
   * عزل المحتوى: إنتاج / عرض تجريبي / اختبار. مستقل عن التوثيق وclaimTrustOk. الافتراضي: اختبار QA. الترقية إلى إنتاج للمراجع/المدير فقط.
   */
  contentClass: 'PRODUCTION' | 'DEMO' | 'QA_TEST';
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * المعاملات الإدارية — سير تحريري Phase 4 على نموذج Phase 3.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  title: string;
  /**
   * معرّف ثابت غير مترجم. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية.
   */
  slug: string;
  /**
   * ملخص قصير للعرض العام.
   */
  summary: string;
  /**
   * Phase 6 — نص مطبَّع مولَّد تلقائياً للمرشّحين. يُزال من الاستجابات العامة عبر afterRead.
   */
  searchText?: string | null;
  publicationStatus?: string | null;
  category: number | Category;
  agency: number | Agency;
  serviceCenters?: (number | ServiceCenter)[] | null;
  audiences?: ('citizen' | 'resident' | 'student' | 'employee' | 'business' | 'visitor' | 'other')[] | null;
  eligibility?: string | null;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  requiredDocuments?:
    | {
        /**
         * مفتاح مستقر للدليل التفاعلي. يُملأ تلقائياً عند الحفظ إن تُرك فارغاً (Phase 8).
         */
        key?: string | null;
        document: number | Document;
        requirementType: 'required' | 'conditional' | 'alternative';
        condition?: string | null;
        quantity?: number | null;
        originalRequired?: boolean | null;
        copiesRequired?: number | null;
        certificationRequired?: boolean | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  steps: {
    /**
     * مفتاح مستقر للدليل التفاعلي. يُملأ تلقائياً عند الحفظ إن تُرك فارغاً (Phase 8).
     */
    key?: string | null;
    title: string;
    description: string;
    locationNote?: string | null;
    id?: string | null;
  }[];
  fees?:
    | {
        /**
         * مفتاح مستقر للدليل التفاعلي. يُملأ تلقائياً عند الحفظ إن تُرك فارغاً (Phase 8).
         */
        key?: string | null;
        label: string;
        amount?: number | null;
        currency?: ('SYP' | 'USD' | 'EUR' | 'other') | null;
        amountText?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  estimatedDuration?: {
    minimum?: number | null;
    maximum?: number | null;
    unit?: ('minutes' | 'hours' | 'business_days' | 'calendar_days' | 'weeks') | null;
    note?: string | null;
  };
  outcome?: string | null;
  prerequisiteProcedures?: (number | Transaction)[] | null;
  sources: {
    source: number | Source;
    primary?: boolean | null;
    /**
     * أقسام المحتوى التي يدعمها هذا المصدر (مفاتيح ثابتة).
     */
    coveredSections?:
      | (
          | 'summary'
          | 'eligibility'
          | 'required_documents'
          | 'steps'
          | 'fees'
          | 'duration'
          | 'service_centers'
          | 'outcome'
          | 'other'
        )[]
      | null;
    citationNote?: string | null;
    id?: string | null;
  }[];
  /**
   * P0-05B1: ادعاءات مطلوبة للاعتماد/النشر الموثوق. المحتوى بلا ربط مطلوب يفشل عند الاعتماد/النشر والعرض العام.
   */
  claimBindings?:
    | {
        claim: number | Claim;
        /**
         * إن وُسم مطلوباً فيجب أن يقيَّم AUTHORITATIVE عند الاعتماد/النشر. WARNING_ONLY لا يكفي.
         */
        required?: boolean | null;
        /**
         * تلميح انتقالي لربط القسم — ليس بديلاً عن تغطية المصادر.
         */
        coveredSection?:
          | (
              | 'summary'
              | 'eligibility'
              | 'required_documents'
              | 'steps'
              | 'fees'
              | 'duration'
              | 'service_centers'
              | 'outcome'
              | 'other'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ذاكرة تخزين مؤقتة / مؤشر تحريري فقط — ليست سلطة الثقة النهائية. العرض العام يتطلب claimTrustOk=true وإعادة تقييم حيّ للادعاءات والمصادر.
   */
  claimTrustOk?: boolean | null;
  /**
   * مطلوب قبل النشر.
   */
  lastReviewedAt?: string | null;
  /**
   * لا تُعاد أبداً في طلبات REST العامة المجهولة. لا تبطل الاعتماد.
   */
  internalNotes?: string | null;
  /**
   * يظهر زر «ابدأ الدليل التفاعلي» فقط عند التفعيل ووجود إعداد دليل صالح بدون أخطاء.
   */
  guideEnabled?: boolean | null;
  questions?:
    | {
        /**
         * أحرف إنجليزية صغيرة وأرقام وشرطة سفلية فقط (مثال: first_time). لا يُغيّر بعد النشر.
         */
        key: string;
        questionType: 'single' | 'multi' | 'boolean';
        prompt: string;
        helpText?: string | null;
        required?: boolean | null;
        active?: boolean | null;
        options?:
          | {
              /**
               * أحرف إنجليزية صغيرة وأرقام وشرطة سفلية فقط (مثال: first_time). لا يُغيّر بعد النشر.
               */
              key: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        visibleWhen?: {
          all?:
            | {
                questionKey: string;
                operator: 'equals' | 'notEquals' | 'includes' | 'exists';
                /**
                 * مطلوبة لـ equals / notEquals / includes. لمفتاح الخيار أو نعم/لا.
                 */
                value?: string | null;
                id?: string | null;
              }[]
            | null;
          any?:
            | {
                questionKey: string;
                operator: 'equals' | 'notEquals' | 'includes' | 'exists';
                /**
                 * مطلوبة لـ equals / notEquals / includes. لمفتاح الخيار أو نعم/لا.
                 */
                value?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  variants?:
    | {
        /**
         * أحرف إنجليزية صغيرة وأرقام وشرطة سفلية فقط (مثال: first_time). لا يُغيّر بعد النشر.
         */
        key: string;
        title: string;
        explanation?: string | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  notices?:
    | {
        /**
         * أحرف إنجليزية صغيرة وأرقام وشرطة سفلية فقط (مثال: first_time). لا يُغيّر بعد النشر.
         */
        key: string;
        title: string;
        body: string;
        severity?: ('info' | 'warning') | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  decisionRules?:
    | {
        /**
         * أحرف إنجليزية صغيرة وأرقام وشرطة سفلية فقط (مثال: first_time). لا يُغيّر بعد النشر.
         */
        key: string;
        /**
         * الأقل يُنفَّذ أولاً؛ الأعلى لاحقاً (يتجاوز عند التعارض).
         */
        priority: number;
        active?: boolean | null;
        explanation?: string | null;
        when?: {
          all?:
            | {
                questionKey: string;
                operator: 'equals' | 'notEquals' | 'includes' | 'exists';
                /**
                 * مطلوبة لـ equals / notEquals / includes. لمفتاح الخيار أو نعم/لا.
                 */
                value?: string | null;
                id?: string | null;
              }[]
            | null;
          any?:
            | {
                questionKey: string;
                operator: 'equals' | 'notEquals' | 'includes' | 'exists';
                /**
                 * مطلوبة لـ equals / notEquals / includes. لمفتاح الخيار أو نعم/لا.
                 */
                value?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        effects: {
          type:
            | 'includeDocument'
            | 'excludeDocument'
            | 'includeStep'
            | 'excludeStep'
            | 'includeFee'
            | 'excludeFee'
            | 'includeNotice'
            | 'excludeNotice'
            | 'selectVariant';
          /**
           * مفتاح وثيقة / خطوة / رسم / ملاحظة / متغير.
           */
          targetKey: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * تُغيَّر عبر إجراءات سير العمل فقط — لا تُعيَّن يدوياً.
   */
  workflowState: 'draft' | 'in_review' | 'changes_requested' | 'approved' | 'published' | 'archived';
  submittedForReviewAt?: string | null;
  submittedForReviewBy?: (number | null) | User;
  changeRequestedAt?: string | null;
  changeRequestedBy?: (number | null) | User;
  /**
   * ظاهر للباحث داخل لوحة الإدارة — غير متاح للعامة.
   */
  changeRequestComment?: string | null;
  approvedAt?: string | null;
  approvedBy?: (number | null) | User;
  /**
   * تقني — مخفي عن الباحث. يُكتب عبر سير العمل فقط.
   */
  approvedContentHash?: string | null;
  approvedVersionId?: string | null;
  /**
   * إن وُجد يتجاوز verificationPolicyDays من إعدادات الموقع.
   */
  reviewIntervalDays?: number | null;
  /**
   * يُحسب عند الاعتماد/النشر. المدير فقط يتجاوزه بسبب موثّق.
   */
  reviewDueAt?: string | null;
  reviewDueOverrideReason?: string | null;
  /**
   * يخفي المعاملة عن العامة حتى عند كونها منشورة.
   */
  markedOutdated?: boolean | null;
  archivedAt?: string | null;
  archivedBy?: (number | null) | User;
  archiveReason?: string | null;
  workflowSchemaVersion?: number | null;
  /**
   * عزل المحتوى: إنتاج / عرض تجريبي / اختبار. مستقل عن التوثيق وclaimTrustOk. الافتراضي: اختبار QA. الترقية إلى إنتاج للمراجع/المدير فقط.
   */
  contentClass: 'PRODUCTION' | 'DEMO' | 'QA_TEST';
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * أسس ادعاءات/أدلة — التخزين فقط في هذه المرحلة. لا تفرض صلاحية النشر على الواجهة العامة بعد.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims".
 */
export interface Claim {
  id: number;
  /**
   * معرّف برمجي ثابت (a-z, 0-9, _). لربط لاحق بالمتطلبات/القواعد.
   */
  key: string;
  /**
   * صياغة موجزة لواقعة خدمة حكومية قابلة للتحقق مستقلاً.
   */
  statement: string;
  /**
   * ملاحظات داخلية — ليست قيمة حكومية ولا تُعرض للعامة.
   */
  editorialNotes?: string | null;
  /**
   * ربط اختياري بالمعاملة المالكة. لا يُلزم كل حقول المعاملة بادعاءات بعد.
   */
  transaction?: (number | null) | Transaction;
  /**
   * تصنيف خفيف للتصفية — ليس أنطولوجيا كاملة.
   */
  kind?: ('requirement' | 'fee' | 'step' | 'eligibility' | 'process' | 'duration' | 'location' | 'other') | null;
  /**
   * تلميح ربط لاحق (وثيقة/خطوة/رسم/قاعدة دليل…) — دون إعادة هيكلة الحقول الآن.
   */
  scopeKind?: ('transaction_section' | 'document_key' | 'step_key' | 'fee_key' | 'guide_rule' | 'other') | null;
  /**
   * مثل مفتاح وثيقة/خطوة/قاعدة. اختياري في P0-05A.
   */
  scopeKey?: string | null;
  /**
   * UNKNOWN و CONFLICTED حالتان صالحتان — لا تُختزلان إلى verified boolean. VERIFIED للمراجع/المدير فقط.
   */
  status:
    | 'DRAFT'
    | 'NEEDS_REVIEW'
    | 'VERIFIED'
    | 'UNKNOWN'
    | 'CONFLICTED'
    | 'NEEDS_OFFICIAL_CONFIRMATION'
    | 'OUTDATED'
    | 'SUPERSEDED'
    | 'REJECTED';
  /**
   * بيانات فقط في P0-05A. PUBLIC / PUBLIC_WITH_WARNING / BLOCKED للمراجع/المدير فقط.
   */
  publicationPermission: 'INTERNAL_ONLY' | 'PUBLIC' | 'PUBLIC_WITH_WARNING' | 'BLOCKED';
  /**
   * يربط بمصادر موجودة. يدعم SUPPORTS و CONTRADICTS معاً (تعارض).
   */
  evidence?:
    | {
        source: number | Source;
        relationType: 'SUPPORTS' | 'CONTRADICTS' | 'PARTIALLY_SUPPORTS' | 'SUPERSEDES' | 'CONTEXT_ONLY';
        note?: string | null;
        quoteOrLocator?: string | null;
        checkedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * يُعيَّن تلقائياً عند التوثيق من المراجع/المدير النشط.
   */
  reviewedBy?: (number | null) | User;
  /**
   * طابع زمني من الخادم عند الانتقال إلى VERIFIED.
   */
  verifiedAt?: string | null;
  validFrom?: string | null;
  validUntil?: string | null;
  reviewDueAt?: string | null;
  /**
   * عزل المحتوى: إنتاج / عرض تجريبي / اختبار. مستقل عن التوثيق وclaimTrustOk. الافتراضي: اختبار QA. الترقية إلى إنتاج للمراجع/المدير فقط.
   */
  contentClass: 'PRODUCTION' | 'DEMO' | 'QA_TEST';
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * سجل تدقيق غير قابل للتعديل — يُكتب من خادم سير العمل فقط.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  actor?: (number | null) | User;
  action:
    | 'draft_created'
    | 'submitted_for_review'
    | 'changes_requested'
    | 'resubmitted_for_review'
    | 'approved'
    | 'approval_invalidated'
    | 'published'
    | 'unpublished'
    | 'archived'
    | 'archive_restored'
    | 'revision_restored'
    | 'review_date_overridden'
    | 'marked_outdated';
  entityType: string;
  entityId: string;
  transaction?: (number | null) | Transaction;
  entityVersionId?: string | null;
  summary: string;
  beforeReference?: string | null;
  afterReference?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'agencies';
        value: number | Agency;
      } | null)
    | ({
        relationTo: 'service-centers';
        value: number | ServiceCenter;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'claims';
        value: number | Claim;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  adminLabel?: T;
  name?: T;
  displayName?: T;
  role?: T;
  isActive?: T;
  preferredLocale?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies_select".
 */
export interface AgenciesSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  slug?: T;
  type?: T;
  description?: T;
  officialWebsite?: T;
  contactEmail?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  mainAddress?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-centers_select".
 */
export interface ServiceCentersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  agency?: T;
  governorate?: T;
  city?: T;
  address?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  workingHours?: T;
  accessibilityNotes?: T;
  latitude?: T;
  longitude?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  description?: T;
  documentType?: T;
  validityNote?: T;
  reusable?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sourceType?: T;
  agency?: T;
  officialUrl?: T;
  archiveUrl?: T;
  referenceNumber?: T;
  issuedAt?: T;
  lastVerifiedAt?: T;
  verificationStatus?: T;
  notes?: T;
  contentClass?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  searchText?: T;
  publicationStatus?: T;
  category?: T;
  agency?: T;
  serviceCenters?: T;
  audiences?: T;
  eligibility?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  requiredDocuments?:
    | T
    | {
        key?: T;
        document?: T;
        requirementType?: T;
        condition?: T;
        quantity?: T;
        originalRequired?: T;
        copiesRequired?: T;
        certificationRequired?: T;
        notes?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        key?: T;
        title?: T;
        description?: T;
        locationNote?: T;
        id?: T;
      };
  fees?:
    | T
    | {
        key?: T;
        label?: T;
        amount?: T;
        currency?: T;
        amountText?: T;
        notes?: T;
        id?: T;
      };
  estimatedDuration?:
    | T
    | {
        minimum?: T;
        maximum?: T;
        unit?: T;
        note?: T;
      };
  outcome?: T;
  prerequisiteProcedures?: T;
  sources?:
    | T
    | {
        source?: T;
        primary?: T;
        coveredSections?: T;
        citationNote?: T;
        id?: T;
      };
  claimBindings?:
    | T
    | {
        claim?: T;
        required?: T;
        coveredSection?: T;
        id?: T;
      };
  claimTrustOk?: T;
  lastReviewedAt?: T;
  internalNotes?: T;
  guideEnabled?: T;
  questions?:
    | T
    | {
        key?: T;
        questionType?: T;
        prompt?: T;
        helpText?: T;
        required?: T;
        active?: T;
        options?:
          | T
          | {
              key?: T;
              label?: T;
              id?: T;
            };
        visibleWhen?:
          | T
          | {
              all?:
                | T
                | {
                    questionKey?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              any?:
                | T
                | {
                    questionKey?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
            };
        id?: T;
      };
  variants?:
    | T
    | {
        key?: T;
        title?: T;
        explanation?: T;
        active?: T;
        id?: T;
      };
  notices?:
    | T
    | {
        key?: T;
        title?: T;
        body?: T;
        severity?: T;
        active?: T;
        id?: T;
      };
  decisionRules?:
    | T
    | {
        key?: T;
        priority?: T;
        active?: T;
        explanation?: T;
        when?:
          | T
          | {
              all?:
                | T
                | {
                    questionKey?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              any?:
                | T
                | {
                    questionKey?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
            };
        effects?:
          | T
          | {
              type?: T;
              targetKey?: T;
              id?: T;
            };
        id?: T;
      };
  workflowState?: T;
  submittedForReviewAt?: T;
  submittedForReviewBy?: T;
  changeRequestedAt?: T;
  changeRequestedBy?: T;
  changeRequestComment?: T;
  approvedAt?: T;
  approvedBy?: T;
  approvedContentHash?: T;
  approvedVersionId?: T;
  reviewIntervalDays?: T;
  reviewDueAt?: T;
  reviewDueOverrideReason?: T;
  markedOutdated?: T;
  archivedAt?: T;
  archivedBy?: T;
  archiveReason?: T;
  workflowSchemaVersion?: T;
  contentClass?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims_select".
 */
export interface ClaimsSelect<T extends boolean = true> {
  key?: T;
  statement?: T;
  editorialNotes?: T;
  transaction?: T;
  kind?: T;
  scopeKind?: T;
  scopeKey?: T;
  status?: T;
  publicationPermission?: T;
  evidence?:
    | T
    | {
        source?: T;
        relationType?: T;
        note?: T;
        quoteOrLocator?: T;
        checkedAt?: T;
        id?: T;
      };
  reviewedBy?: T;
  verifiedAt?: T;
  validFrom?: T;
  validUntil?: T;
  reviewDueAt?: T;
  contentClass?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  transaction?: T;
  entityVersionId?: T;
  summary?: T;
  beforeReference?: T;
  afterReference?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * إعدادات عامة للمنصة — تُستهلك في الواجهة العامة (Phase 5).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  independenceDisclaimer: string;
  footerDisclaimer?: string | null;
  contactEmail?: string | null;
  supportPhone?: string | null;
  /**
   * مهلة مراجعة تحريرية داخلية — ليست موعداً عاماً.
   */
  verificationPolicyDays?: number | null;
  /**
   * يعرض رسالة صيانة على الواجهة العامة — لوحة /admin تبقى متاحة.
   */
  maintenanceMode?: boolean | null;
  /**
   * شرائح أمثلة تحت حقل البحث — نص عربي قصير.
   */
  searchExamples?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * لا تُعرض للعامة إلا إن وُجدت روابط HTTP(S) صالحة.
   */
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  homePageSections?: {
    showCategories?: boolean | null;
    showFeatured?: boolean | null;
    showHowItWorks?: boolean | null;
    showTrust?: boolean | null;
  };
  /**
   * يُعرض ٤–٦ عند التوفّر — فقط السجلات العامة الصالحة.
   */
  featuredTransactions?: (number | Transaction)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  independenceDisclaimer?: T;
  footerDisclaimer?: T;
  contactEmail?: T;
  supportPhone?: T;
  verificationPolicyDays?: T;
  maintenanceMode?: T;
  searchExamples?:
    | T
    | {
        text?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  homePageSections?:
    | T
    | {
        showCategories?: T;
        showFeatured?: T;
        showHowItWorks?: T;
        showTrust?: T;
      };
  featuredTransactions?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}