/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    agencies: Agency;
    'service-centers': ServiceCenter;
    documents: Document;
    sources: Source;
    transactions: Transaction;
    claims: Claim;
    'user-reports': UserReport;
    'audit-events': AuditEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    agencies: AgenciesSelect<false> | AgenciesSelect<true>;
    'service-centers': ServiceCentersSelect<false> | ServiceCentersSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    claims: ClaimsSelect<false> | ClaimsSelect<true>;
    'user-reports': UserReportsSelect<false> | UserReportsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  adminLabel?: string | null;
  name?: string | null;
  displayName?: string | null;
  /**
   * admin · reviewer · researcher · viewer — الباحث لا ينشر. المراجع والمدير ينشران.
   */
  role: 'admin' | 'reviewer' | 'researcher' | 'viewer';
  isActive?: boolean | null;
  preferredLocale?: ('ar' | 'en') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * معرّف ثابت في الرابط العام. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية. أبقِه مستقراً بعد الاستخدام — تغييره يكسر الروابط المحفوظة.
   */
  slug: string;
  description?: string | null;
  /**
   * اتركه فارغاً إن لم يكن هناك تصنيف أب (يُعرض: بدون تصنيف أب).
   */
  parent?: (number | null) | Category;
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً. فضّل الأرشفة عبر سير العمل على الحذف النهائي.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies".
 */
export interface Agency {
  id: number;
  name: string;
  shortName?: string | null;
  /**
   * معرّف ثابت في الرابط العام. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية. أبقِه مستقراً بعد الاستخدام — تغييره يكسر الروابط المحفوظة.
   */
  slug: string;
  type: 'ministry' | 'directorate' | 'public_institution' | 'municipality' | 'syndicate' | 'university' | 'other';
  description?: string | null;
  officialWebsite?: string | null;
  contactEmail?: string | null;
  phones?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  mainAddress?: string | null;
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً. فضّل الأرشفة عبر سير العمل على الحذف النهائي.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-centers".
 */
export interface ServiceCenter {
  id: number;
  name: string;
  /**
   * معرّف ثابت في الرابط العام. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية. أبقِه مستقراً بعد الاستخدام — تغييره يكسر الروابط المحفوظة.
   */
  slug: string;
  agency: number | Agency;
  /**
   * قائمة ثابتة — لا يُستنتج موقع المستخدم تلقائياً.
   */
  governorate:
    | 'damascus'
    | 'rif_dimashq'
    | 'aleppo'
    | 'homs'
    | 'hama'
    | 'latakia'
    | 'tartus'
    | 'idlib'
    | 'deir_ez_zor'
    | 'al_hasakah'
    | 'al_raqqah'
    | 'daraa'
    | 'as_suwayda'
    | 'quneitra';
  city: string;
  address: string;
  phones?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  workingHours?: string | null;
  accessibilityNotes?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً. فضّل الأرشفة عبر سير العمل على الحذف النهائي.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * وثائق يحتاجها المواطن للمعاملات — ليست ملفات مرفوعة.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  name: string;
  /**
   * معرّف ثابت في الرابط العام. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية. أبقِه مستقراً بعد الاستخدام — تغييره يكسر الروابط المحفوظة.
   */
  slug: string;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  documentType?:
    | (
        | 'identity'
        | 'civil_record'
        | 'application'
        | 'photograph'
        | 'receipt'
        | 'certificate'
        | 'approval'
        | 'contract'
        | 'form'
        | 'other'
      )
    | null;
  validityNote?: string | null;
  reusable?: boolean | null;
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً. فضّل الأرشفة عبر سير العمل على الحذف النهائي.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  title: string;
  /**
   * معرّف ثابت في الرابط العام. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية. أبقِه مستقراً بعد الاستخدام — تغييره يكسر الروابط المحفوظة.
   */
  slug: string;
  sourceType:
    | 'official_webpage'
    | 'law'
    | 'decree'
    | 'decision'
    | 'circular'
    | 'official_form'
    | 'official_pdf'
    | 'announcement'
    | 'other';
  agency?: (number | null) | Agency;
  officialUrl: string;
  archiveUrl?: string | null;
  referenceNumber?: string | null;
  issuedAt?: string | null;
  lastVerifiedAt?: string | null;
  verificationStatus: 'needs_review' | 'verified' | 'outdated' | 'unavailable';
  /**
   * ملاحظات تحريرية — لا تُعرض للعامة.
   */
  notes?: string | null;
  /**
   * عزل المحتوى — لا يثبت صحة المعلومة ولا يغني عن توثيق الادعاءات. PRODUCTION: للمحتوى العام المعتمد (ليس تحققاً تلقائياً). DEMO: يظهر بتحذير واضح. QA_TEST: لا يظهر للعامة أبداً. مستقل عن claimTrustOk وعن حالة التحرير. الترقية إلى PRODUCTION للمراجع/المدير فقط.
   */
  contentClass: 'PRODUCTION' | 'DEMO' | 'QA_TEST';
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً. فضّل الأرشفة عبر سير العمل على الحذف النهائي.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * المعاملات الإدارية — نظّم المحتوى عبر التبويبات. التصنيف والنشر وسير العمل في الشريط الجانبي. المحتوى المعبّأ ليس موثّقاً تلقائياً.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  /**
   * يظهر هذا النص للمواطن في العنوان والقوائم.
   */
  title: string;
  /**
   * معرّف ثابت في الرابط العام. أحرف عربية/لاتينية صغيرة وشرطات فقط. بدون لاحقة عشوائية. أبقِه مستقراً بعد الاستخدام — تغييره يكسر الروابط المحفوظة.
   */
  slug: string;
  /**
   * ملخص قصير يظهر للمواطن. تعبئته لا تعني أن المعلومة موثّقة.
   */
  summary: string;
  /**
   * تصنيف للمواطن والتنقّل — قيمة تنظيمية داخل النظام أيضاً.
   */
  category: number | Category;
  /**
   * الجهة المرتبطة بالمعاملة كما تُعرض للمواطن.
   */
  agency: number | Agency;
  /**
   * معلومة للمواطن عن أماكن التنفيذ إن وُجدت.
   */
  serviceCenters?: (number | ServiceCenter)[] | null;
  /**
   * لمن تُوجَّه هذه المعاملة — معلومة تنظيمية/عرضية للمواطن.
   */
  audiences?: ('citizen' | 'resident' | 'student' | 'employee' | 'business' | 'visitor' | 'other')[] | null;
  /**
   * أسماء شائعة تساعد البحث. ليست عنواناً رسمياً بديلاً.
   */
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * معلومة للمواطن عن من يحق له تقديم الطلب.
   */
  eligibility?: string | null;
  /**
   * معلومة للمواطن عن ناتج المعاملة المتوقع.
   */
  outcome?: string | null;
  /**
   * تقدير للمواطن — ليس تعهداً رسمياً من الجهة.
   */
  estimatedDuration?: {
    minimum?: number | null;
    maximum?: number | null;
    unit?: ('minutes' | 'hours' | 'business_days' | 'calendar_days' | 'weeks') | null;
    note?: string | null;
  };
  /**
   * معلومة للمواطن عن معاملات يجب إنجازها أولاً.
   */
  prerequisiteProcedures?: (number | Transaction)[] | null;
  /**
   * قائمة للمواطن. نوع المتطلب والمفتاح المستقر قيم داخلية للدليل — لا تعني موافقة رسمية.
   */
  requiredDocuments?:
    | {
        /**
         * مفتاح تقني للدليل التفاعلي (ليس نصاً للمواطن). يُملأ تلقائياً عند الحفظ إن تُرك فارغاً. لا تغيّره بعد ربطه بالقواعد إلا عند الضرورة.
         */
        key?: string | null;
        /**
         * معلومة للمواطن عبر بطاقة الوثيقة المرتبطة.
         */
        document: number | Document;
        /**
         * يساعد الدليل والنتيجة — لا يعني بحد ذاته أن الجهة الرسمية قبلت الورقة.
         */
        requirementType: 'required' | 'conditional' | 'alternative';
        condition?: string | null;
        quantity?: number | null;
        originalRequired?: boolean | null;
        copiesRequired?: number | null;
        certificationRequired?: boolean | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * خطوات يراها المواطن. المفتاح المستقر تقني للدليل التفاعلي.
   */
  steps: {
    /**
     * مفتاح تقني للدليل التفاعلي. يُملأ تلقائياً عند الحفظ إن تُرك فارغاً. لا تغيّره بعد ربطه بالقواعد إلا عند الضرورة.
     */
    key?: string | null;
    /**
     * يظهر هذا النص للمواطن.
     */
    title: string;
    /**
     * يظهر هذا النص للمواطن.
     */
    description: string;
    locationNote?: string | null;
    id?: string | null;
  }[];
  /**
   * معلومة للمواطن عن الرسوم. تعبئتها لا تثبت أن الرسوم سارية دون مصدر وادعاء موثوق.
   */
  fees?:
    | {
        /**
         * مفتاح تقني للدليل التفاعلي. يُملأ تلقائياً عند الحفظ إن تُرك فارغاً. لا تغيّره بعد ربطه بالقواعد إلا عند الضرورة.
         */
        key?: string | null;
        /**
         * يظهر هذا النص للمواطن.
         */
        label: string;
        amount?: number | null;
        currency?: ('SYP' | 'USD' | 'EUR' | 'other') | null;
        amountText?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * أسئلة يراها المواطن في الدليل التفاعلي. المفتاح المستقر تقني؛ نص السؤال هو ما يظهر للعامة.
   */
  questions?:
    | {
        /**
         * قيمة تقنية للنظام (وليس نصاً للمواطن). أحرف إنجليزية صغيرة وأرقام وشرطة سفلية فقط. لا تغيّره بعد ربطه بالقواعد أو بعد استخدام الدليل إلا عند الضرورة — التغيير قد يكسر القواعد أو التقدّم المحفوظ على أجهزة المواطنين.
         */
        key: string;
        questionType: 'single' | 'multi' | 'boolean';
        /**
         * يظهر هذا النص للمواطن.
         */
        prompt: string;
        /**
         * اختياري — مساعدة قصيرة للمواطن تحت السؤال.
         */
        helpText?: string | null;
        required?: boolean | null;
        /**
         * الأسئلة غير النشطة لا تظهر في الدليل العام.
         */
        active?: boolean | null;
        /**
         * التسمية للمواطن؛ المفتاح تقني للقواعد.
         */
        options?:
          | {
              /**
               * قيمة تقنية للنظام (وليس نصاً للمواطن). أحرف إنجليزية صغيرة وأرقام وشرطة سفلية فقط. لا تغيّره بعد ربطه بالقواعد أو بعد استخدام الدليل إلا عند الضرورة — التغيير قد يكسر القواعد أو التقدّم المحفوظ على أجهزة المواطنين.
               */
              key: string;
              /**
               * يظهر هذا النص للمواطن.
               */
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * شروط ظهور السؤال حسب إجابات سابقة (مفاتيح تقنية).
         */
        visibleWhen?: {
          all?:
            | {
                /**
                 * المفتاح المستقر للسؤال (تقني) — ليس نص السؤال الظاهر للمواطن.
                 */
                questionKey: string;
                operator: 'equals' | 'notEquals' | 'includes' | 'exists';
                /**
                 * مطلوبة لـ equals / notEquals / includes. استخدم مفتاح الخيار أو yes/no للأسئلة المنطقية.
                 */
                value?: string | null;
                id?: string | null;
              }[]
            | null;
          any?:
            | {
                /**
                 * المفتاح المستقر للسؤال (تقني) — ليس نص السؤال الظاهر للمواطن.
                 */
                questionKey: string;
                operator: 'equals' | 'notEquals' | 'includes' | 'exists';
                /**
                 * مطلوبة لـ equals / notEquals / includes. استخدم مفتاح الخيار أو yes/no للأسئلة المنطقية.
                 */
                value?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * مسارات نتيجة اختيارية يختارها محرك القرار عبر selectVariant.
   */
  variants?:
    | {
        /**
         * قيمة تقنية للنظام (وليس نصاً للمواطن). أحرف إنجليزية صغيرة وأرقام وشرطة سفلية فقط. لا تغيّره بعد ربطه بالقواعد أو بعد استخدام الدليل إلا عند الضرورة — التغيير قد يكسر القواعد أو التقدّم المحفوظ على أجهزة المواطنين.
         */
        key: string;
        /**
         * يظهر هذا النص للمواطن في النتيجة عند اختيار المتغير.
         */
        title: string;
        explanation?: string | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ملاحظات/تنبيهات يمكن تضمينها في نتيجة الدليل حسب القواعد.
   */
  notices?:
    | {
        /**
         * قيمة تقنية للنظام (وليس نصاً للمواطن). أحرف إنجليزية صغيرة وأرقام وشرطة سفلية فقط. لا تغيّره بعد ربطه بالقواعد أو بعد استخدام الدليل إلا عند الضرورة — التغيير قد يكسر القواعد أو التقدّم المحفوظ على أجهزة المواطنين.
         */
        key: string;
        title: string;
        body: string;
        severity?: ('info' | 'warning') | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * منطق التضمين/الاستبعاد حسب الإجابات. استخدم مفاتيح الوثائق/الخطوات/الرسوم/الملاحظات/المتغيرات — لا تغيّر المفاتيح المرتبطة دون مراجعة.
   */
  decisionRules?:
    | {
        /**
         * قيمة تقنية للنظام (وليس نصاً للمواطن). أحرف إنجليزية صغيرة وأرقام وشرطة سفلية فقط. لا تغيّره بعد ربطه بالقواعد أو بعد استخدام الدليل إلا عند الضرورة — التغيير قد يكسر القواعد أو التقدّم المحفوظ على أجهزة المواطنين.
         */
        key: string;
        /**
         * الأقل يُنفَّذ أولاً؛ الأعلى لاحقاً (يتجاوز عند التعارض).
         */
        priority: number;
        active?: boolean | null;
        /**
         * اختياري — قد يظهر كسبب («لماذا») في نتيجة الدليل.
         */
        explanation?: string | null;
        when?: {
          all?:
            | {
                /**
                 * المفتاح المستقر للسؤال (تقني) — ليس نص السؤال الظاهر للمواطن.
                 */
                questionKey: string;
                operator: 'equals' | 'notEquals' | 'includes' | 'exists';
                /**
                 * مطلوبة لـ equals / notEquals / includes. استخدم مفتاح الخيار أو yes/no للأسئلة المنطقية.
                 */
                value?: string | null;
                id?: string | null;
              }[]
            | null;
          any?:
            | {
                /**
                 * المفتاح المستقر للسؤال (تقني) — ليس نص السؤال الظاهر للمواطن.
                 */
                questionKey: string;
                operator: 'equals' | 'notEquals' | 'includes' | 'exists';
                /**
                 * مطلوبة لـ equals / notEquals / includes. استخدم مفتاح الخيار أو yes/no للأسئلة المنطقية.
                 */
                value?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        effects: {
          type:
            | 'includeDocument'
            | 'excludeDocument'
            | 'includeStep'
            | 'excludeStep'
            | 'includeFee'
            | 'excludeFee'
            | 'includeNotice'
            | 'excludeNotice'
            | 'selectVariant';
          /**
           * المفتاح المستقر لوثيقة / خطوة / رسم / ملاحظة / متغير.
           */
          targetKey: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * مراجع قابلة للاقتباس. مطلوبة للنشر. لا تغني عن ربط الادعاءات المطلوبة ولا عن ثقة الادعاء الحيّة.
   */
  sources: {
    /**
     * مرجع قابل للاقتباس. المصدر ≠ الادعاء. ملء مصدر لا يثبت صحة المحتوى ولا يُجيز النشر وحده.
     */
    source: number | Source;
    /**
     * تلميح تحريري للمصدر الرئيسي — ليس اعتماداً رسمياً ولا بديلاً عن ربط الادعاءات.
     */
    primary?: boolean | null;
    /**
     * أقسام المحتوى التي يدعمها هذا المصدر (مفاتيح ثابتة للنظام — ليست نصاً للمواطن).
     */
    coveredSections?:
      | (
          | 'summary'
          | 'eligibility'
          | 'required_documents'
          | 'steps'
          | 'fees'
          | 'duration'
          | 'service_centers'
          | 'outcome'
          | 'other'
        )[]
      | null;
    /**
     * اختياري — يظهر للفريق التحريري؛ ليس دليلاً على التحقق.
     */
    citationNote?: string | null;
    id?: string | null;
  }[];
  /**
   * ادعاءات مطلوبة تشارك في فحوصات ثقة النشر (خادم). المصدر وحده لا يكفي. VERIFIED على الادعاء ≠ نشر المعاملة تلقائياً. contentClass مستقل عن هذه الروابط.
   */
  claimBindings?:
    | {
        /**
         * الادعاء ≠ المصدر. اختر ادعاءً موثّقاً؛ المصدر وحده لا يكفي للنشر العام.
         */
        claim: number | Claim;
        /**
         * إن وُسم مطلوباً فيجب أن يقيَّم AUTHORITATIVE عند الاعتماد/النشر. WARNING_ONLY لا يكفي. هذا لا يغيّر تصنيف المحتوى (contentClass).
         */
        required?: boolean | null;
        /**
         * تلميح تحريري لربط القسم — ليس بديلاً عن تغطية المصادر ولا عن ثقة الادعاء.
         */
        coveredSection?:
          | (
              | 'summary'
              | 'eligibility'
              | 'required_documents'
              | 'steps'
              | 'fees'
              | 'duration'
              | 'service_centers'
              | 'outcome'
              | 'other'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * تاريخ آخر مراجعة تحريرية. مطلوب قبل النشر. لا يثبت وحده صحة كل الادعاءات.
   */
  lastReviewedAt?: string | null;
  /**
   * للفريق فقط — لا تُعاد للعامة. لا تبطل الاعتماد ولا تغيّر contentClass.
   */
  internalNotes?: string | null;
  /**
   * ظاهر للباحث داخل لوحة الإدارة — غير متاح للعامة.
   */
  changeRequestComment?: string | null;
  /**
   * يُسجَّل عند تجاوز الموعد من المدير — للقراءة فقط هنا.
   */
  reviewDueOverrideReason?: string | null;
  /**
   * سبب موثّق للأرشفة عبر سير العمل — ليس حذفاً نهائياً. الأرشفة مفضّلة على الحذف.
   */
  archiveReason?: string | null;
  /**
   * قيمة داخلية للنظام — مولَّدة تلقائياً للبحث. لا تُعرض للعامة عبر REST.
   */
  searchText?: string | null;
  /**
   * ملخّص عرضي لحالة المسودة/النشر — يُشتق تلقائياً وليس بديلاً عن سير العمل.
   */
  publicationStatus?: string | null;
  /**
   * مؤشر تحريري مخزَّن فقط — ليست سلطة الثقة النهائية. العرض العام يعيد تقييم الادعاءات والمصادر حياً. لا يغني عن contentClass.
   */
  claimTrustOk?: boolean | null;
  /**
   * يظهر زر «ابدأ الدليل التفاعلي» للمواطن فقط عند التفعيل ووجود أسئلة/قواعد صالحة بدون أخطاء.
   */
  guideEnabled?: boolean | null;
  /**
   * تُغيَّر عبر أزرار سير العمل فقط — ليست تعديلاً يدوياً للحالة.
   */
  workflowState: 'draft' | 'in_review' | 'changes_requested' | 'approved' | 'published' | 'archived';
  submittedForReviewAt?: string | null;
  submittedForReviewBy?: (number | null) | User;
  changeRequestedAt?: string | null;
  changeRequestedBy?: (number | null) | User;
  approvedAt?: string | null;
  approvedBy?: (number | null) | User;
  /**
   * تقني — مخفي عن الباحث. يُكتب عبر سير العمل فقط.
   */
  approvedContentHash?: string | null;
  approvedVersionId?: string | null;
  /**
   * إن وُجد يتجاوز verificationPolicyDays من إعدادات الموقع.
   */
  reviewIntervalDays?: number | null;
  /**
   * يُحسب عند الاعتماد/النشر. المدير فقط يتجاوزه بسبب موثّق.
   */
  reviewDueAt?: string | null;
  /**
   * يخفي المعاملة عن العامة حتى عند كونها منشورة. الأرشفة عبر سير العمل مفضّلة على الحذف النهائي.
   */
  markedOutdated?: boolean | null;
  archivedAt?: string | null;
  archivedBy?: (number | null) | User;
  workflowSchemaVersion?: number | null;
  /**
   * عزل المحتوى — لا يثبت صحة المعلومة ولا يغني عن توثيق الادعاءات. PRODUCTION: للمحتوى العام المعتمد (ليس تحققاً تلقائياً). DEMO: يظهر بتحذير واضح. QA_TEST: لا يظهر للعامة أبداً. مستقل عن claimTrustOk وعن حالة التحرير. الترقية إلى PRODUCTION للمراجع/المدير فقط.
   */
  contentClass: 'PRODUCTION' | 'DEMO' | 'QA_TEST';
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً. فضّل الأرشفة عبر سير العمل على الحذف النهائي.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * أسس ادعاءات/أدلة — التخزين فقط في هذه المرحلة. لا تفرض صلاحية النشر على الواجهة العامة بعد.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims".
 */
export interface Claim {
  id: number;
  /**
   * معرّف برمجي ثابت (a-z, 0-9, _). لربط لاحق بالمتطلبات/القواعد.
   */
  key: string;
  /**
   * صياغة موجزة لواقعة خدمة حكومية قابلة للتحقق مستقلاً.
   */
  statement: string;
  /**
   * ملاحظات داخلية — ليست قيمة حكومية ولا تُعرض للعامة.
   */
  editorialNotes?: string | null;
  /**
   * ربط اختياري بالمعاملة المالكة. لا يُلزم كل حقول المعاملة بادعاءات بعد.
   */
  transaction?: (number | null) | Transaction;
  /**
   * تصنيف خفيف للتصفية — ليس أنطولوجيا كاملة.
   */
  kind?: ('requirement' | 'fee' | 'step' | 'eligibility' | 'process' | 'duration' | 'location' | 'other') | null;
  /**
   * تلميح ربط لاحق (وثيقة/خطوة/رسم/قاعدة دليل…) — دون إعادة هيكلة الحقول الآن.
   */
  scopeKind?: ('transaction_section' | 'document_key' | 'step_key' | 'fee_key' | 'guide_rule' | 'other') | null;
  /**
   * مثل مفتاح وثيقة/خطوة/قاعدة. اختياري في P0-05A.
   */
  scopeKey?: string | null;
  /**
   * UNKNOWN و CONFLICTED حالتان صالحتان — لا تُختزلان إلى verified boolean. VERIFIED للمراجع/المدير فقط.
   */
  status:
    | 'DRAFT'
    | 'NEEDS_REVIEW'
    | 'VERIFIED'
    | 'UNKNOWN'
    | 'CONFLICTED'
    | 'NEEDS_OFFICIAL_CONFIRMATION'
    | 'OUTDATED'
    | 'SUPERSEDED'
    | 'REJECTED';
  /**
   * بيانات فقط في P0-05A. PUBLIC / PUBLIC_WITH_WARNING / BLOCKED للمراجع/المدير فقط.
   */
  publicationPermission: 'INTERNAL_ONLY' | 'PUBLIC' | 'PUBLIC_WITH_WARNING' | 'BLOCKED';
  /**
   * يربط بمصادر موجودة. يدعم SUPPORTS و CONTRADICTS معاً (تعارض).
   */
  evidence?:
    | {
        source: number | Source;
        relationType: 'SUPPORTS' | 'CONTRADICTS' | 'PARTIALLY_SUPPORTS' | 'SUPERSEDES' | 'CONTEXT_ONLY';
        note?: string | null;
        quoteOrLocator?: string | null;
        checkedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * يُعيَّن تلقائياً عند التوثيق من المراجع/المدير النشط.
   */
  reviewedBy?: (number | null) | User;
  /**
   * طابع زمني من الخادم عند الانتقال إلى VERIFIED.
   */
  verifiedAt?: string | null;
  validFrom?: string | null;
  validUntil?: string | null;
  reviewDueAt?: string | null;
  /**
   * عزل المحتوى — لا يثبت صحة المعلومة ولا يغني عن توثيق الادعاءات. PRODUCTION: للمحتوى العام المعتمد (ليس تحققاً تلقائياً). DEMO: يظهر بتحذير واضح. QA_TEST: لا يظهر للعامة أبداً. مستقل عن claimTrustOk وعن حالة التحرير. الترقية إلى PRODUCTION للمراجع/المدير فقط.
   */
  contentClass: 'PRODUCTION' | 'DEMO' | 'QA_TEST';
  /**
   * المحتوى غير النشط لا يظهر للعامة حتى لو كان منشوراً. فضّل الأرشفة عبر سير العمل على الحذف النهائي.
   */
  active?: boolean | null;
  createdBy?: (number | null) | User;
  lastUpdatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * بلاغات المواطنين عن معلومات تغيّرت — ليست محتوى عاماً. بيانات التواصل محمية للمراجع/المدير فقط.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-reports".
 */
export interface UserReport {
  id: number;
  /**
   * المعاملة التي يخصّها البلاغ.
   */
  transaction: number | Transaction;
  section: 'documents' | 'fees' | 'steps' | 'location' | 'duration' | 'source' | 'other';
  /**
   * نص عادي من المواطن — لا يُعرض للعامة.
   */
  message: string;
  sourceUrl?: string | null;
  /**
   * اختياري — للمتابعة بشأن البلاغ فقط. لا يُعرض للعامة. لا تُعدّل من لوحة التحرير عادةً.
   */
  contactEmail?: string | null;
  /**
   * اختياري — للمتابعة بشأن البلاغ فقط. لا يُعرض للعامة.
   */
  contactPhone?: string | null;
  consentAccepted: boolean;
  /**
   * مفتوح → قيد المراجعة → تم الحل / مرفوض / مزعج.
   */
  status: 'open' | 'in_review' | 'resolved' | 'rejected' | 'spam';
  /**
   * ملاحظات الفريق — لا تُرسل للمواطن تلقائياً.
   */
  reviewNotes?: string | null;
  /**
   * مطلوب عند الإغلاق أو الرفض.
   */
  resolutionSummary?: string | null;
  resolvedAt?: string | null;
  resolvedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * سجل تدقيق غير قابل للتعديل — يُكتب من خادم سير العمل فقط.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  actor?: (number | null) | User;
  action:
    | 'draft_created'
    | 'submitted_for_review'
    | 'changes_requested'
    | 'resubmitted_for_review'
    | 'approved'
    | 'approval_invalidated'
    | 'published'
    | 'unpublished'
    | 'archived'
    | 'archive_restored'
    | 'revision_restored'
    | 'review_date_overridden'
    | 'marked_outdated'
    | 'report_received'
    | 'report_in_review'
    | 'report_resolved'
    | 'report_rejected'
    | 'report_marked_spam'
    | 'report_status_changed';
  entityType: string;
  entityId: string;
  transaction?: (number | null) | Transaction;
  entityVersionId?: string | null;
  summary: string;
  beforeReference?: string | null;
  afterReference?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'agencies';
        value: number | Agency;
      } | null)
    | ({
        relationTo: 'service-centers';
        value: number | ServiceCenter;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'claims';
        value: number | Claim;
      } | null)
    | ({
        relationTo: 'user-reports';
        value: number | UserReport;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  adminLabel?: T;
  name?: T;
  displayName?: T;
  role?: T;
  isActive?: T;
  preferredLocale?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies_select".
 */
export interface AgenciesSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  slug?: T;
  type?: T;
  description?: T;
  officialWebsite?: T;
  contactEmail?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  mainAddress?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-centers_select".
 */
export interface ServiceCentersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  agency?: T;
  governorate?: T;
  city?: T;
  address?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  workingHours?: T;
  accessibilityNotes?: T;
  latitude?: T;
  longitude?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  description?: T;
  documentType?: T;
  validityNote?: T;
  reusable?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sourceType?: T;
  agency?: T;
  officialUrl?: T;
  archiveUrl?: T;
  referenceNumber?: T;
  issuedAt?: T;
  lastVerifiedAt?: T;
  verificationStatus?: T;
  notes?: T;
  contentClass?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  category?: T;
  agency?: T;
  serviceCenters?: T;
  audiences?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  eligibility?: T;
  outcome?: T;
  estimatedDuration?:
    | T
    | {
        minimum?: T;
        maximum?: T;
        unit?: T;
        note?: T;
      };
  prerequisiteProcedures?: T;
  requiredDocuments?:
    | T
    | {
        key?: T;
        document?: T;
        requirementType?: T;
        condition?: T;
        quantity?: T;
        originalRequired?: T;
        copiesRequired?: T;
        certificationRequired?: T;
        notes?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        key?: T;
        title?: T;
        description?: T;
        locationNote?: T;
        id?: T;
      };
  fees?:
    | T
    | {
        key?: T;
        label?: T;
        amount?: T;
        currency?: T;
        amountText?: T;
        notes?: T;
        id?: T;
      };
  questions?:
    | T
    | {
        key?: T;
        questionType?: T;
        prompt?: T;
        helpText?: T;
        required?: T;
        active?: T;
        options?:
          | T
          | {
              key?: T;
              label?: T;
              id?: T;
            };
        visibleWhen?:
          | T
          | {
              all?:
                | T
                | {
                    questionKey?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              any?:
                | T
                | {
                    questionKey?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
            };
        id?: T;
      };
  variants?:
    | T
    | {
        key?: T;
        title?: T;
        explanation?: T;
        active?: T;
        id?: T;
      };
  notices?:
    | T
    | {
        key?: T;
        title?: T;
        body?: T;
        severity?: T;
        active?: T;
        id?: T;
      };
  decisionRules?:
    | T
    | {
        key?: T;
        priority?: T;
        active?: T;
        explanation?: T;
        when?:
          | T
          | {
              all?:
                | T
                | {
                    questionKey?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              any?:
                | T
                | {
                    questionKey?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
            };
        effects?:
          | T
          | {
              type?: T;
              targetKey?: T;
              id?: T;
            };
        id?: T;
      };
  sources?:
    | T
    | {
        source?: T;
        primary?: T;
        coveredSections?: T;
        citationNote?: T;
        id?: T;
      };
  claimBindings?:
    | T
    | {
        claim?: T;
        required?: T;
        coveredSection?: T;
        id?: T;
      };
  lastReviewedAt?: T;
  internalNotes?: T;
  changeRequestComment?: T;
  reviewDueOverrideReason?: T;
  archiveReason?: T;
  searchText?: T;
  publicationStatus?: T;
  claimTrustOk?: T;
  guideEnabled?: T;
  workflowState?: T;
  submittedForReviewAt?: T;
  submittedForReviewBy?: T;
  changeRequestedAt?: T;
  changeRequestedBy?: T;
  approvedAt?: T;
  approvedBy?: T;
  approvedContentHash?: T;
  approvedVersionId?: T;
  reviewIntervalDays?: T;
  reviewDueAt?: T;
  markedOutdated?: T;
  archivedAt?: T;
  archivedBy?: T;
  workflowSchemaVersion?: T;
  contentClass?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims_select".
 */
export interface ClaimsSelect<T extends boolean = true> {
  key?: T;
  statement?: T;
  editorialNotes?: T;
  transaction?: T;
  kind?: T;
  scopeKind?: T;
  scopeKey?: T;
  status?: T;
  publicationPermission?: T;
  evidence?:
    | T
    | {
        source?: T;
        relationType?: T;
        note?: T;
        quoteOrLocator?: T;
        checkedAt?: T;
        id?: T;
      };
  reviewedBy?: T;
  verifiedAt?: T;
  validFrom?: T;
  validUntil?: T;
  reviewDueAt?: T;
  contentClass?: T;
  active?: T;
  createdBy?: T;
  lastUpdatedBy?: T;
  publishedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-reports_select".
 */
export interface UserReportsSelect<T extends boolean = true> {
  transaction?: T;
  section?: T;
  message?: T;
  sourceUrl?: T;
  contactEmail?: T;
  contactPhone?: T;
  consentAccepted?: T;
  status?: T;
  reviewNotes?: T;
  resolutionSummary?: T;
  resolvedAt?: T;
  resolvedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  transaction?: T;
  entityVersionId?: T;
  summary?: T;
  beforeReference?: T;
  afterReference?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * إعدادات عامة للمنصة — تُستهلك في الواجهة العامة (Phase 5).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  independenceDisclaimer: string;
  footerDisclaimer?: string | null;
  contactEmail?: string | null;
  supportPhone?: string | null;
  /**
   * مهلة مراجعة تحريرية داخلية — ليست موعداً عاماً.
   */
  verificationPolicyDays?: number | null;
  /**
   * يعرض رسالة صيانة على الواجهة العامة — لوحة /admin تبقى متاحة.
   */
  maintenanceMode?: boolean | null;
  /**
   * شرائح أمثلة تحت حقل البحث — نص عربي قصير.
   */
  searchExamples?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * لا تُعرض للعامة إلا إن وُجدت روابط HTTP(S) صالحة.
   */
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  homePageSections?: {
    showCategories?: boolean | null;
    showFeatured?: boolean | null;
    showHowItWorks?: boolean | null;
    showTrust?: boolean | null;
  };
  /**
   * يُعرض ٤–٦ عند التوفّر — فقط السجلات العامة الصالحة.
   */
  featuredTransactions?: (number | Transaction)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  independenceDisclaimer?: T;
  footerDisclaimer?: T;
  contactEmail?: T;
  supportPhone?: T;
  verificationPolicyDays?: T;
  maintenanceMode?: T;
  searchExamples?:
    | T
    | {
        text?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  homePageSections?:
    | T
    | {
        showCategories?: T;
        showFeatured?: T;
        showHowItWorks?: T;
        showTrust?: T;
      };
  featuredTransactions?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}